version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.1.0
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:3.1.0
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  khermes:
    image: ardlema/khermes:0.102
    network_mode: host
    depends_on:
      - zookeeper
      - kafka